# Generated by Django 5.0.6 on 2024-06-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="champion_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="character",
            name="character_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="class_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="faction_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="is_vampire",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="is_werewolf",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="character",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="character",
            name="race_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
