# Generated by Django 5.0.6 on 2024-06-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0002_alter_character_champion_points_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="id",
        ),
        migrations.AlterField(
            model_name="character",
            name="character_id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
